# Generated by Django 3.2 on 2021-04-22 13:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210422_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isbn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_title', models.CharField(max_length=25)),
                ('book_title', models.CharField(max_length=50)),
                ('isbn_number', models.IntegerField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.isbn'),
        ),
    ]
