# Generated by Django 3.2 on 2021-04-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210422_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.CharField(blank=True, default='7169194384', editable=False, max_length=10, unique=True),
        ),
    ]
