# Generated by Django 3.2 on 2021-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_isbn_isbn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.CharField(blank=True, default='1574425748', editable=False, max_length=10, unique=True),
        ),
    ]
